from sqlachemy import Column, Integer, String, Float, Numeric, Date, LargeBinary
from app.database import Base

class Producto(Base):
    __tablename__ = "PRODUCTO"
    __table_args__ = {"schema": "DATA_USR"}
    
    PRO_EMPRESA = Column(Integer, primary_key=True, nullable=False)
    PRO_CODIGO = Column(Integer, primary_key=True, nullable=False)
    PRO_ID = Column(String(20), nullable=False)
    PRO_NOMBRE = Column(String(100), nullable=False)
    PRO_INVENTARIO = Column(Integer)
    PRO_TPRODUCTO = Column(Integer)
    PRO_CTA_INVENTARIO = Column(Integer)
    PRO_CTA_VENTA = Column(Integer)
    PRO_CTA_COSTO = Column(Integer)
    PRO_PORC_COMISION = Column(Numeric(5, 2))
    PRO_STOCK_MINIMO = Column(Integer)
    PRO_STOCK_MAXIMO = Column(Integer)
    PRO_UNIDAD = Column(Integer, nullable=False)
    PRO_IMPUESTO = Column(Integer)
    PRO_FECHA_LANZAM = Column(Date)
    PRO_FECHA_VENCE = Column(Date)
    PRO_NIVEL = Column(Integer, nullable=False)
    PRO_SERIE = Column(Integer)
    PRO_PESO = Column(Numeric(9, 2))
    PRO_INFSERIE = Column(Integer)
    PRO_INACTIVO = Column(Integer)
    PRO_PROVEEDOR = Column(Integer)
    CREA_USR = Column(String(10))
    CREA_FECHA = Column(Date)
    MOD_USR = Column(String(10))
    MOD_FECHA = Column(Date)
    PRO_UBICACION = Column(Integer)
    PRO_ULT_COSTO = Column(Numeric(23, 10))
    PRO_GPRODUCTO = Column(Integer, nullable=False)
    PRO_ALCOHOL = Column(Integer)
    PRO_GRADO = Column(Numeric(17, 4))
    PRO_CRITICO = Column(Integer, default=0)
    PRO_ENVASE = Column(Integer)
    PRO_TRANSPORTE = Column(Integer)
    PRO_ICE1 = Column(String(10))
    PRO_ICE2 = Column(String(10))
    PRO_ICE3 = Column(String(10))
    PRO_ICE4 = Column(String(10))
    PRO_ICE5 = Column(String(10))
    PRO_BUFFER = Column(Integer)
    PRO_ID1 = Column(String(50))
    PRO_MARCA = Column(Integer)
    PRO_CTA_INVENTARIO1 = Column(Integer)
    PRO_CTA_VENTA1 = Column(Integer)
    PRO_CTA_COSTO1 = Column(Integer)
    PRO_PROCEDENCIA = Column(Integer)
    PRO_DETALLE = Column(Integer)
    PRO_MODELO_PRODUCTO = Column(Integer)
    PRO_GRUPO_ORDEN = Column(Integer)
    PRO_CODIGO_ORDEN = Column(Integer)
    PRO_CAMBIA_PRECIO_YN = Column(String(1))
    PRO_TALLA = Column(Integer)
    PRO_COLOR = Column(Integer)
    PRO_CALIFICACION = Column(String(1))
    PRO_GARANTIA = Column(Integer)
    PRO_TIPOEMBALA = Column(Integer)
    PRO_TIEMPO = Column(Integer)
    PRO_PORC_SEGURIDAD = Column(Numeric(5, 2))
    PRO_ABREVIATURA = Column(String(50))
    PRO_CODBARRAS = Column(String(20))
    PRO_ESTRUCTURA = Column(Integer)
    PRO_CLASE = Column(Integer)
    PRO_DESTINO = Column(Integer)
    PRO_CLIENTE = Column(Integer)
    PRO_UMEDIDA_FAB = Column(Integer)
    PRO_PATRON_RUTA = Column(Integer)
    PRO_LPRODUCTO = Column(Integer)
    PRO_SLPRODUCTO = Column(Integer)
    PRO_CENTRO = Column(Integer)
    PRO_LARGO = Column(Integer)
    PRO_ANCHO = Column(Integer)
    PRO_ALTURA = Column(Integer)
    PRO_PESO_BRUTO = Column(Integer)
    PRO_PESO_NETO = Column(Integer)
    PRO_PESO_ESPECIFICO = Column(Integer)
    PRO_PESO_TOTAL = Column(Integer)
    PRO_ESPESOR = Column(Integer)
    PRO_DIAMETRO = Column(Integer)
    PRO_SALIDA_GRANEL = Column(Integer)
    PRO_COSTEO = Column(Integer)
    PRO_FOTO = Column(LargeBinary)
    PRO_ESPECIFICA = Column(Integer)
    PRO_LOTE_NP = Column(Integer)
    PRO_GS1CE = Column(Integer)
    PRO_TIPOSCRAP = Column(Integer)
    PRO_COSTOSCRAP = Column(Numeric(17, 4))
    PRO_SECCION = Column(Integer)
    PRO_PFCOLSEC = Column(Integer)
    PRO_MODPRODUCCION = Column(Integer)
    PRO_MAQUILA = Column(Integer)
    PRO_MIGRADO = Column(String(10))
    PRO_NOCONSUMO = Column(Integer)
    PRO_ARO = Column(Integer)
    PRO_SUBMODELO = Column(Integer)
    PRO_GENERO = Column(Integer)
    PRO_ULT_FECHA_COMPRA = Column(Date)
    PRO_LINEA = Column(Integer)
    PRO_FOTOPROD = Column(Integer)
    PRO_VALIDASTOCK = Column(Integer)
    PRO_FOTO_S = Column(Integer)
    PRO_PRECIO1 = Column(Numeric(17, 4))
    PRO_PRECIO2 = Column(Numeric(17, 4))
    PRO_PRECIO3 = Column(Numeric(17, 4))
    PRO_ALTO = Column(String(100))
    PRO_LARGO1 = Column(String(100))
    PRO_ANCHO1 = Column(String(100))
    PRO_CAPACIDAD = Column(String(100))
    PRO_NOMBRE_ADUANA = Column(String(100))
    PRO_CARGA_WEB = Column(Integer)
    PRO_MINIMO_WEB = Column(Numeric(17, 4))
    PRO_COD_ORDEN = Column(String(20))
    PRO_CARGA_EXTERNO = Column(Integer)